sudo: required

language: cpp

services:
  - docker

install:
  - docker pull mreichelt/carnd-cpp

script:
  - docker run -v "`pwd`:/project" mreichelt/carnd-cpp /bin/bash -c 'mkdir -p build && cd build && cmake .. && make -j4 && ./test/Test'
